const SELECT_CURRENT_NAV = "SELECT_CURRENT_NAV";
const TOGGLE_MOBILE_NAV = "TOGGLE_MOBILE_NAV";
const RESIZE_WINDOW = "RESIZE_WINDOW";

export { SELECT_CURRENT_NAV, TOGGLE_MOBILE_NAV, RESIZE_WINDOW };
